---
- name: Configure HLH AI engine
  hosts: hlh_ai_engine
  become: true
  vars:
    hlh_offline: false

  tasks:
    - name: Run AI engine bootstrap script inside target LXC
      ansible.builtin.script: ../files/configure-ai-engine-inside-lxc.sh
      environment:
        HLH_OFFLINE: "{{ (hlh_offline | bool) | ternary('1', '0') }}"
