all:
  children:
    docker_hosts:
      hosts:
        docker-host:
          ansible_host: 192.168.6.240
          ansible_user: ops
    ai_vms:
      hosts:
        ai-vm:
          ansible_host: 192.168.6.253
          ansible_user: ops
    proxmox_hosts:
      hosts:
        hlh-proxmox:
          ansible_host: 192.168.6.10
          ansible_user: root
