---
container_runtime_provider: docker
service_orchestrator_provider: docker_compose

service_orchestrator_commands:
  docker_compose:
    binary: docker
    subcommand: compose
  dockhand:
    binary: dockhand
    subcommand: compose
