---
services_root_dir: /opt/hlh/services
service_orchestrator_provider: docker_compose

service_orchestrator_commands:
  docker_compose:
    binary: docker
    subcommand: compose
  dockhand:
    binary: dockhand
    subcommand: compose

hlh_service_stacks:
  - name: openspeedtest
    source_dir: "{{ playbook_dir }}/../../services/openspeedtest"
    compose_file: docker-compose.yml
  - name: uptime-kuma
    source_dir: "{{ playbook_dir }}/../../services/uptime-kuma"
    compose_file: docker-compose.yml
