---
services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    environment:
      - MODE=standalone
      - WEB_PORT=80
    networks:
      macvlan_net:
        ipv4_address: 192.168.1.20

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: macvlan0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
