---
- name: Install dockhand runtime package
  ansible.builtin.apt:
    name: "{{ dockhand_package_name }}"
    state: present
    update_cache: true

- name: Ensure dockhand users are present in docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ dockhand_users }}"
